name: UBI9 OpenJDK 11 S2I Image CI
on: [push, pull_request]
env:
  LANG: en_US.UTF-8
  IMAGE: openjdk-11-rhel-9
jobs:
  call-openjdkci:
    uses: ./.github/workflows/image-workflow-template.yml
    with:
      image: openjdk-11-rhel-9
